version: "3.3"

services:
  rethinkdb:
    image: rethinkdb:latest
    container_name: rethinkdb
    ports:
      - "38080:8080"
      - "38015:28015"
      - "39015:29015"
    volumes:
      - ./rethinkdb:/data
    deploy:
      resources:
        limits:
          cpus: '0.80'
          memory: 2000M
        reservations:
          cpus: '0.80'
          memory: 2000M

  # postgres:
  #   image: postgres
  #   container_name: postgres
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #   volumes:
  #     - ./postgres:/var/lib/postgresql/data
  #   ports:
  #     - '5432:5432'
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.80'
  #         memory: 2000M
  #       reservations:
  #         cpus: '0.80'
  #         memory: 2000M

  app:
    build: .
    container_name: app
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    command: npm start
    ports:
      - "33000:3000"
    environment:
      DB_SCHEMA: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
    depends_on:
      - rethinkdb
      # - postgres
